name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build amlich
      run: cd amlich && cargo build --verbose
    - name: Run amlich tests
      run: cd amlich && cargo test --verbose
    - name: Build vncalendar
      run: cd vncalendar && cargo build --verbose
    - name: Run vncalendar tests
      run: cd vncalendar && cargo test --verbose
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
